export * from './aiEngine'
export * from './crashLogger'
export * from './haptics'
export { SoundProvider, useSoundContext } from './SoundContext'
export * from './sounds'
export * from './storageService'
export { ThemeProvider, useThemeContext } from './ThemeContext'
export { default as useAutoReset } from './useAutoReset'
export { default as useCoinFlipAnimation } from './useCoinFlipAnimation'
export { default as useCpuPlayer } from './useCpuPlayer'
export { default as useDropdownBehavior } from './useDropdownBehavior'
export { default as useGameBoard } from './useGameBoard'
export { default as useGameOrchestration } from './useGameOrchestration'
export { default as useGameStats } from './useGameStats'
export { default as useGridKeyboard } from './useGridKeyboard'
export { default as useNotificationQueue } from './useNotificationQueue'
export { useOnlineStatus } from './useOnlineStatus'
export { default as usePrevious } from './usePrevious'
export { default as useSeries } from './useSeries'
export { default as useSmartPosition } from './useSmartPosition'
export { default as useSoundEffects } from './useSoundEffects'
export { useStats } from './useStats'
// Custom gestures removed due to conflicts with existing codebase
// export { useSwipeGesture } from './useSwipeGesture'
// export { useLongPress } from './useLongPress'
// export { useSwipe } from './useSwipe' // hook not found
export { useAppScreens } from './useAppScreens'
export { useDeviceInfo } from './useDeviceInfo'
export { useKeyboardControls } from './useKeyboardControls'
export { useLongPress } from './useLongPress'
export { useMediaQuery } from './useMediaQuery'
export { logWebVitals, usePerformanceMetrics } from './usePerformanceMetrics'
export { useResponsiveState } from './useResponsiveState'
export { useServiceLoader } from './useServiceLoader'
export { useTicTacToe } from './useTicTacToe'
export { default as useWebWorker } from './useWebWorker'
export { useWindowSize } from './useWindowSize'
export type { WindowSize } from './useWindowSize'
