// ═══════════════════════════════════════════════════════════════════════════
// WASM Build Pipeline
//
// 1. Compile AssemblyScript → .wasm binary
// 2. Encode .wasm to base64 → TypeScript module
//
// The base64-embedded approach eliminates fetch/URL issues across all
// platforms (browser, Electron file://, Capacitor WebView, blob Workers).
//
// Usage: pnpm wasm:build
// ═══════════════════════════════════════════════════════════════════════════

import { execSync } from 'child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

// ── 1. Ensure output directories ──────────────────────────────────────────
mkdirSync('build', { recursive: true })
mkdirSync('src/wasm', { recursive: true })

// ── 2. Compile AssemblyScript → WASM ──────────────────────────────────────
console.log('Compiling AssemblyScript → WASM...')

const isDebug = process.argv.includes('--debug')
const ascFlags = isDebug
  ? '--debug --runtime stub'
  : '--optimize --runtime stub --noAssert'

const asc = resolve('node_modules/.bin/asc')

execSync(
  `${asc} assembly/index.ts --outFile build/ai.wasm ${ascFlags}`,
  { stdio: 'inherit' },
)

// ── 3. Encode WASM binary → base64 TypeScript module ──────────────────────
const wasm = readFileSync('build/ai.wasm')
const base64 = wasm.toString('base64')
const sizeBytes = wasm.length
const sizeKB = (sizeBytes / 1024).toFixed(1)

writeFileSync(
  'src/wasm/ai-wasm.ts',
  [
    '// Auto-generated by scripts/build-wasm.js — do not edit manually',
    '// Rebuild with: pnpm wasm:build',
    `// Source: assembly/index.ts → build/ai.wasm (${sizeKB} KB, ${sizeBytes} bytes)`,
    '',
    `export const AI_WASM_BASE64 = '${base64}';`,
    '',
  ].join('\n'),
)

console.log(
  `✓ WASM AI engine: ${sizeBytes} bytes (${sizeKB} KB) → src/wasm/ai-wasm.ts`,
)
